# Generated by Django 2.1 on 2018-10-07 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.IntegerField()),
                ('list_name', models.CharField(max_length=30)),
                ('list_count', models.IntegerField()),
                ('time', models.IntegerField()),
                ('list_image', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('part1', models.BooleanField(default=True)),
                ('part2', models.BooleanField(default=False)),
                ('part3', models.BooleanField(default=False)),
                ('part4', models.BooleanField(default=False)),
                ('part5', models.BooleanField(default=False)),
                ('part6', models.BooleanField(default=False)),
                ('part7', models.BooleanField(default=False)),
                ('part8', models.BooleanField(default=False)),
            ],
        ),
    ]
