# Generated by Django 2.1 on 2018-10-07 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_list', '0001_initial'),
        ('recommend_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendlist',
            name='video_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_list', to='video_list.VideoList'),
        ),
    ]
