# Generated by Django 2.1 on 2018-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_list', '0002_recommendlist_video_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendlist',
            name='part0',
            field=models.BooleanField(default=True, verbose_name='전신'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part1',
            field=models.BooleanField(default=False, verbose_name='목 / 어깨'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part2',
            field=models.BooleanField(default=False, verbose_name='가슴'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part3',
            field=models.BooleanField(default=False, verbose_name='복부 / 허리'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part4',
            field=models.BooleanField(default=False, verbose_name='허벅지 / 무릎'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part5',
            field=models.BooleanField(default=False, verbose_name='종아리 / 발목'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part6',
            field=models.BooleanField(default=False, verbose_name='팔 / 손목'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part7',
            field=models.BooleanField(default=False, verbose_name='등'),
        ),
        migrations.AlterField(
            model_name='recommendlist',
            name='part8',
            field=models.BooleanField(default=False, verbose_name='엉덩이'),
        ),
    ]
