# Generated by Django 2.1 on 2018-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_list', '0005_remove_recommendlist_video_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendlist',
            name='list_image',
            field=models.ImageField(upload_to='recommend_image/'),
        ),
    ]
