# Generated by Django 2.1 on 2018-11-23 06:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('age', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('is_man', models.BooleanField(default=True)),
                ('activity_level', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('interested_part', models.CharField(default='1;2;3', max_length=20)),
                ('comment', models.CharField(blank=True, default='comment', max_length=30)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('favorite_list', models.CharField(default='1;2;3', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekdays_start', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('weekdays_end', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('weekend_start', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('weekend_end', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('is_push_weekdays', models.BooleanField(default=True)),
                ('is_push_weekend', models.BooleanField(default=True)),
                ('is_subscription', models.BooleanField(default=True)),
                ('phone_model', models.CharField(blank=True, max_length=300, null=True)),
                ('push_id', models.CharField(blank=True, max_length=300, null=True)),
                ('part0', models.IntegerField(default=0, verbose_name='전신')),
                ('part1', models.IntegerField(default=0, verbose_name='목 / 어깨')),
                ('part2', models.IntegerField(default=0, verbose_name='가슴')),
                ('part3', models.IntegerField(default=0, verbose_name='복부 / 허리')),
                ('part4', models.IntegerField(default=0, verbose_name='허벅지 / 무릎')),
                ('part5', models.IntegerField(default=0, verbose_name='종아리 / 발목')),
                ('part6', models.IntegerField(default=0, verbose_name='팔 / 손목')),
                ('part7', models.IntegerField(default=0, verbose_name='등')),
                ('part8', models.IntegerField(default=0, verbose_name='엉덩이')),
                ('prev_video_id', models.IntegerField(default=0)),
                ('next_video_id', models.IntegerField(default=0)),
                ('weekdays_prev_hour', models.IntegerField(default=0)),
                ('weekdays_next_hour', models.IntegerField(default=0)),
                ('weekend_prev_hour', models.IntegerField(default=0)),
                ('weekend_next_hour', models.IntegerField(default=0)),
                ('weekdays_push_list', models.CharField(default='0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27', max_length=1000)),
                ('weekend_push_list', models.CharField(default='0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
