# Generated by Django 2.1 on 2018-10-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='next_hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='next_video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part0',
            field=models.IntegerField(default=0, verbose_name='전신'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part1',
            field=models.IntegerField(default=0, verbose_name='목 / 어깨'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part2',
            field=models.IntegerField(default=0, verbose_name='가슴'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part3',
            field=models.IntegerField(default=0, verbose_name='복부 / 허리'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part4',
            field=models.IntegerField(default=0, verbose_name='허벅지 / 무릎'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part5',
            field=models.IntegerField(default=0, verbose_name='종아리 / 발목'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part6',
            field=models.IntegerField(default=0, verbose_name='팔 / 손목'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part7',
            field=models.IntegerField(default=0, verbose_name='등'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='part8',
            field=models.IntegerField(default=0, verbose_name='엉덩이'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='prev_hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='prev_video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weekdays_push_list',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weekend_push_list',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
