# Generated by Django 2.1 on 2018-08-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20180822_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='favorite_list',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interested_part',
            field=models.CharField(max_length=20),
        ),
    ]
