# Generated by Django 2.1 on 2018-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20181008_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='next_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='next_video_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='prev_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='prev_video_id',
            field=models.IntegerField(default=0),
        ),
    ]
