# Generated by Django 2.1 on 2018-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20180829_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='comment',
            field=models.CharField(default='comment', max_length=12),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='favorite_list',
            field=models.CharField(default='1;2;3;', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interested_part',
            field=models.CharField(default='1;2;3', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='name', max_length=10),
        ),
    ]
