# Generated by Django 2.1 on 2018-11-28 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20181128_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_man',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.IntegerField(choices=[(1, '남자'), (2, '여자')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='성별'),
        ),
    ]
