# Generated by Django 2.1 on 2018-12-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20181128_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='interested_part',
            field=models.CharField(blank=True, default='1;2;3', max_length=20, verbose_name='관심 부위'),
        ),
    ]
