# Generated by Django 2.1 on 2018-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20181009_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='next_hour',
            new_name='weekdays_next_hour',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='prev_hour',
            new_name='weekdays_prev_hour',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weekend_next_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weekend_prev_hour',
            field=models.IntegerField(default=0),
        ),
    ]
