# Generated by Django 2.1 on 2018-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_auto_20181010_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_model',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='push_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
