# Generated by Django 2.1 on 2018-10-01 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part1', models.IntegerField(default=0)),
                ('part2', models.IntegerField(default=0)),
                ('part3', models.IntegerField(default=0)),
                ('part4', models.IntegerField(default=0)),
                ('part5', models.IntegerField(default=0)),
                ('part6', models.IntegerField(default=0)),
                ('part7', models.IntegerField(default=0)),
                ('part8', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
