# Generated by Django 2.1 on 2018-09-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20180902_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='part',
        ),
        migrations.AddField(
            model_name='video',
            name='part1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='part2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='part3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='part4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='part5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='part6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='part7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='part8',
            field=models.BooleanField(default=False),
        ),
    ]
