# Generated by Django 2.1 on 2018-10-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20181008_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
