# Generated by Django 2.1 on 2018-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20181009_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(upload_to='video_thumbnail/'),
        ),
    ]
