# Generated by Django 2.1 on 2018-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20181118_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sub_part',
            field=models.IntegerField(blank=True, default=0, verbose_name='부 운동부위'),
        ),
    ]
