# Generated by Django 2.1 on 2018-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20181124_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sub_part',
            field=models.IntegerField(default=0, null=True, verbose_name='부 운동부위'),
        ),
    ]
