# Generated by Django 2.1 on 2018-11-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20181124_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='main_part',
            field=models.IntegerField(choices=[(0, '전신'), (1, '목 / 어깨'), (2, '가슴'), (3, '복부 / 허리'), (4, '허벅지 / 무릎'), (5, '종아리 / 발목'), (6, '팔 / 손목'), (7, '등'), (8, '엉덩이')], default=0, verbose_name='주 운동부위'),
        ),
        migrations.AlterField(
            model_name='video',
            name='sub_part',
            field=models.IntegerField(choices=[(0, '전신'), (1, '목 / 어깨'), (2, '가슴'), (3, '복부 / 허리'), (4, '허벅지 / 무릎'), (5, '종아리 / 발목'), (6, '팔 / 손목'), (7, '등'), (8, '엉덩이')], default=0, null=True, verbose_name='부 운동부위'),
        ),
    ]
