# Generated by Django 2.1 on 2018-12-01 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20181127_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='level',
            field=models.IntegerField(choices=[(1, '저'), (2, '중'), (3, '고')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='운동 수준'),
        ),
        migrations.AlterField(
            model_name='video',
            name='sub_part',
            field=models.IntegerField(choices=[(0, '전신'), (1, '목 / 어깨'), (2, '가슴'), (3, '복부 / 허리'), (4, '허벅지 / 무릎'), (5, '종아리 / 발목'), (6, '팔 / 손목'), (7, '등'), (8, '엉덩이'), (9, '없음')], default=0, null=True, verbose_name='부 운동부위'),
        ),
    ]
